### ISSUE TITLE
how to test on my own data. 

### ISSUE THREAD

**Issue by songhc8** [AlexSunNik/ReDC#1]
Thanks for sharing. 

could you please release the inference script. i.e. if I got one rgb image and corresponding depth image. how can I get the inference result.

**Comment by AlexSunNik** [comment]
Hello! Sorry for the late response.
For inference and eval, you could refer to the gen_test_preds.py file which was used by us to generate official KITTI benchmark results. Let me know if it does not work for you!

**Comment by songhc8** [comment]
It works. Thanks.
